Hancock
PaulHancock/SM2017 pull request #8
Opened 2019-09-11 05:21 UTC by PaulHancock

This is the version that is used in the submitted paper. Making a pull request so that we can eventually merge all our branches.

2019-09-13 06:47 UTC, EGCharlton commented on lib/SM2017.py
> +        top = 1 / (gal_h/2 * np.abs(np.sin(phi)))
This should be top =  (gal_h/2. / np.abs(np.sin(phi)))

2019-09-13 07:34 UTC, EGCharlton requested changes
Looks good to me, just the one distance distance change in SM2017

2019-09-18 07:57 UTC, PaulHancock commented on lib/SM2017.py
> +        top = 1 / (gal_h/2 * np.abs(np.sin(phi)))
This is fixed in a6eb7f7

2019-09-18 08:00 UTC, EGCharlton approved these changes

2019-09-18 08:01 UTC, merged